[package]
name = "ambrogio_bin"
edition = "2021"
# Version is automatically updated -- think twice before changing it
version = "0.8.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open_meteo = { path = "../open_meteo" }
ambrogio_users = { path = "../users" }
ambrogio_core = { path = "../core" }
chrono = { version = "0.4" }
chrono-tz = { version = "0.6" }
derive_more = "0.99"
log = "0.4"
pretty_env_logger = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
serde = "1.0"
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
regex = "1.9.4"
async-trait = "0.1.73"
redis = "0.23.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["std", "fmt", "json"] }
async-once-cell = "0.5.3"
url = "2.4.0"
ngrok = { version = "0.13.1", features = ["axum"] }
axum = "0.6.20"
itertools = "0.11.0"
async-process = "2.0.0"
