volumes:
  redis:
  mongo:

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
        - redis:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
  mongo:
    image: mongo:7.0.12
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: ambrogio
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - mongo:/data/db
