volumes:
  redis:

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
        - redis:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
