[package]
name = "ambrogio_users"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
serde = {version =  "1.0", features = ["derive"]}
serde_json = "1.0"
async-trait = "0.1.73"
derive_builder = "0.12.0"
redis = { version = "0.23.3", features = ["r2d2", "tokio-comp"] }