[package]
name = "users"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
log = "0.4"
pretty_env_logger = "0.4"
serde_json = "1.0"
serde = "1.0"
async-trait = "0.1.73"
derive_builder = "0.12.0"
redis = { version = "0.23.3", features = ["r2d2", "tokio-comp"] }