name: "Do you really want to touch info.rs?"

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize
    paths: 
      - bin/src/info.rs

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: '0'
      - name: Complain if info.rs is edited
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch -a
          git checkout --track origin/${{ github.base_ref }}
          git checkout ${{ github.head_ref }}
          echo "Head: ${{ github.head_ref }}"
          echo "Base: ${{ github.base_ref }}"
          echo ""
          if !(git diff --exit-code ${{ github.base_ref }} ${{ github.head_ref }} -- bin/src/info.rs) ; then 
            gh pr review $PR_NUMBER -c -b 'Are you sure you want to touch `bin/src/info.rs`? 🤔 cc @MrSchyzo'
          else
            echo "✅ No edits in info.rs"
          fi
