name: Label Checker
on:
  pull_request:
    types: [opened, labeled, unlabeled, edited, synchronize, reopened]
    branches: master
    paths-ignore:
      - '.github/**'
      - '.git*'
      - 'git_config/**'
      - 'docs/**'
      - 'Makefile'
      - '**.md'

jobs:
  check_labels:
    name: Require label
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}